In [2]:
import pandas as pd
df = pd.read_csv("replace_old_to_active_stations.csv")
df

,station,lat,lon,nearest_station,dis_from_nearest_station,capacity,station_number
0,Lynn & 19th St North,38.897279,-77.070772,Lynn St & 19th St North,0.019611,27.0,31014
1,Connecticut Ave & Newark St NW / Cleveland Park,38.934236,-77.057663,Connecticut Ave & Macomb St NW / Cleveland Park,0.067510,11.0,31305
2,21st & M St NW,38.905837,-77.046658,New Hampshire Ave & Ward Pl NW,0.058703,19.0,31212
3,Columbia Pike & S Taylor St,38.858311,-77.103614,Columbia Pike & George Mason Dr,0.177073,15.0,31923
4,East Falls Church Metro/Sycamore St & 19th St N,38.884747,-77.155952,East Falls Church Metro / Sycamore St & 19th St N,0.076445,19.0,31904
...,...,...,...,...,...,...,...
111,6th & S Ball St,38.844194,-77.051357,Potomac Ave & 35th St S,0.073495,15.0,31090
112,Reston Station,38.946593,-77.339404,Wiehle Ave & Reston Station Blvd,0.002729,19.0,32215
113,Solutions & Greensboro Dr,38.922435,-77.230343,Greensboro & Pinnacle Dr,0.002931,13.0,32202
114,9th & F St NW / National Portrait Gallery,38.897474,-77.024143,7th & F St NW / National Portrait Gallery,0.169981,27.0,31232
115,8th & F St NW / National Portrait Gallery,38.897105,-77.023110,7th & F St NW / National Portrait Gallery,0.082036,27.0,31232

In [37]:
    #df2 = pd.read_parquet("bike_data.parquet")
df2["Start_station"].nunique()

667

In [9]:
df2.columns

Index(['Duration', 'Start_date', 'End_date', 'Start_station_number',
       'Start_station', 'End_station_number', 'End_station', 'Bike_number',
       'Member_type', 'ride_id'],
      dtype='object')

In [26]:
df3 = pd.read_csv("202203-capitalbikeshare-tripdata.csv")
df3.groupby("start_station_name").agg({"start_lat":"mean","start_lng":"mean"})

                                                    start_lat  start_lng
start_station_name
10th & E St NW                                      38.895916 -77.026043
10th & Florida Ave NW                               38.920386 -77.025669
10th & G St NW                                      38.898255 -77.026232
10th & H St NE                                      38.899982 -76.992720
10th & K St NW                                      38.902422 -77.026225
...                                                       ...        ...
Wisconsin Ave & O St NW                             38.908489 -77.063597
Woodglen Dr & Executive Blvd                        39.043168 -77.113497
Woodley Park Metro / Calvert St & Connecticut A...  38.923394 -77.051831
Woodmont Ave & Strathmore St                        38.979873 -77.093516
Yuma St & Tenley Circle NW                          38.946185 -77.080580

[681 rows x 2 columns]

In [27]:
tmp2 = df2["Start_station"].unique()
tmp3 = df3.start_station_name.unique()

In [35]:
print(len(tmp2),len(tmp3),len(set(tmp3).union(tmp2)))

667 682 799